# Generated by Django 4.2.6 on 2023-12-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='models_year',
            new_name='model_year',
        ),
    ]
