# Generated by Django 4.2.7 on 2023-12-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
